// AUTO-GENERATED by `npm run sync-galleries` from https://xtincell.pixieset.com/
// Manual edits to `category` are preserved across syncs (matched by slug).
// Re-run the sync command to refresh covers, titles, dates, and lock state.

export type Gallery = {
  slug: string;
  title: string;
  cover: string; // images.pixieset.com URL
  date?: string;
  category?: string;
  locked?: boolean;
  bgPosition?: string; // CSS background-position fine-tune
};

const PIXIESET_BASE = 'https://xtincell.pixieset.com';

export const galleryUrl = (g: Gallery) => `${PIXIESET_BASE}/${g.slug}/`;

export const GALLERIES: Gallery[] = [
  {
    slug: 'shevolution',
    title: 'Shevolution',
    cover: 'https://images.pixieset.com/30132099/5dba44cb1eee64b76de6a31f9ad66536-large.jpg',
    date: '6 sept. 2025',
    category: 'Événement',
  },
  {
    slug: 'kmerotakufestival23',
    title: 'Kmer Otaku Festival \'23',
    cover: 'https://images.pixieset.com/82730879/540e2a0d5884ffe7deed7c0cb49a871d-large.jpg',
    category: 'Festival · Pop culture',
  },
  {
    slug: 'kmerotakufestival22',
    title: 'Kmer Otaku Festival \'22',
    cover: 'https://images.pixieset.com/71079779/9fdd66239d7bc8289eb266eca5f09f8b-large.jpg',
    category: 'Festival · Pop culture',
  },
  {
    slug: 'kmerotakufestival25',
    title: 'Kmer Otaku Festival \'25',
    cover: 'https://images.pixieset.com/63711479/68cb3234250f445966fc5390a479c01c-large.jpg',
    category: 'Festival · Pop culture',
  },
  {
    slug: 'kmerotakufestival24',
    title: 'K-mer Otaku Festival 2024',
    cover: 'https://images.pixieset.com/91708787/eb9fe0a4ae92ced2ba6c6c851b919d53-large.jpg',
    date: '3 août 2024',
    category: 'Festival · Pop culture',
    bgPosition: '50% 39%',
  },
  {
    slug: 'ammco',
    title: 'AMMCO',
    cover: 'https://images.pixieset.com/28983067/03b10d60d53f89dfd6637bb28b3f0559-large.jpg',
    category: 'Corporate',
  },
  {
    slug: 'weddingtefoue',
    title: 'Wedding : Tefoue',
    cover: 'https://images.pixieset.com/94640447/2a64eff51a3133dc2054fc403a650599-large.jpg',
    date: '30 déc. 2023',
    category: 'Mariage',
    bgPosition: '57% 35%',
  },
  {
    slug: 'h3riq',
    title: 'H3riQ',
    cover: 'https://images.pixieset.com/92979347/6529184208ddd8898765f3829eb2ffa8-large.jpg',
    category: 'Portrait · Musique',
    bgPosition: '36% 14%',
  },
  {
    slug: 'roadtripnord-1',
    title: 'RoadTrip Nord',
    cover: 'https://images.pixieset.com/81559347/2747c9e75ec231d7125cc99ef3becf92-large.jpg',
    category: 'Reportage',
    bgPosition: '49% 73%',
  },
  {
    slug: 'afrobit',
    title: 'AfroBit',
    cover: 'https://images.pixieset.com/02359347/25ea342e00b9e27799759ac24f912ac4-large.jpg',
    category: 'Événement',
    bgPosition: '54% 19%',
  },
  {
    slug: 'locko',
    title: 'Locko',
    cover: 'https://images.pixieset.com/00546347/2f91b10e3e9dfefef6f3efec084c67d5-large.jpg',
    category: 'Portrait · Musique',
    bgPosition: '38% 7%',
  },
  {
    slug: 'mounpoubeyi',
    title: 'Mounpoubeyi',
    cover: 'https://images.pixieset.com/28625347/c9b793ef13a3e69046b40c010e8b5496-large.jpg',
    category: 'Portrait',
    bgPosition: '52% 43%',
  },
  {
    slug: 'wondje',
    title: 'AD & Emily',
    cover: 'https://images.pixieset.com/92190837/3166059c5d1561a144aa5ce6689aa1b6-large.jpg',
    date: '21 déc. 2023',
    category: 'Mariage',
    bgPosition: '53% 32%',
  },
  {
    slug: 'lydol',
    title: 'Lydol',
    cover: 'https://images.pixieset.com/85473637/e8b3d225bc413fe41b844b82c45a751a-large.jpg',
    category: 'Portrait · Musique',
  },
  {
    slug: 'prenatalshotmarieclaire',
    title: 'Prenatal Shot : Marie Claire',
    cover: 'https://images.pixieset.com/15753637/72c758d00e092d40b8824aa5b3d9cf79-large.jpg',
    category: 'Portrait',
  },
  {
    slug: 'cabinetdentaire',
    title: 'Cabinet Dentaire BeauSourire',
    cover: 'https://images.pixieset.com/87102637/6d4974e00fbed7b4a9705557d6452253-large.jpg',
    category: 'Corporate',
    bgPosition: '73% 18%',
  },
  {
    slug: 'briceandstephanie',
    title: 'Brice & Stephanie',
    cover: 'https://images.pixieset.com/03837537/34ea4d2e91d4807368b8cee4efd5af06-large.jpg',
    category: 'Mariage',
    locked: true,
    bgPosition: '49% 19%',
  },
  {
    slug: 'wedding',
    title: 'Brice & Sandra',
    cover: 'https://images.pixieset.com/41045537/dd0519a4b1c2033291f1d192df79fb78-large.jpg',
    date: '12 avr. 2024',
    category: 'Mariage',
    locked: true,
  },
];
