// AUTO-GENERATED by `npm run sync-galleries` from YouTube RSS.
// Re-run the sync command to refresh the latest videos.

export type YouTubeVideo = {
  id: string;
  title: string;
  date?: string;
  thumb: string;
  watchUrl: string;
};

export const SOCIAL_PROFILES = {
  youtube: 'https://youtube.com/@x-tincell',
  instagram: 'https://instagram.com/xtincell',
  facebook: 'https://facebook.com/xtincell',
  youtubeChannelId: 'UCRl8fgAoMc7dJupcoSPZ3xw',
} as const;

export const YOUTUBE_VIDEOS: YouTubeVideo[] = [
  {
    id: '8qV9-ziRNhE',
    title: 'Noise : Ep 02',
    date: '9 déc. 2024',
    thumb: 'https://i.ytimg.com/vi/8qV9-ziRNhE/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=8qV9-ziRNhE',
  },
  {
    id: 'lhd7ynhv3AM',
    title: 'Episode Pilote : Noise',
    date: '2 déc. 2024',
    thumb: 'https://i.ytimg.com/vi/lhd7ynhv3AM/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=lhd7ynhv3AM',
  },
  {
    id: 'VJoAl1HA_qw',
    title: 'Aquannick -Opening 1 - original french version',
    date: '6 nov. 2024',
    thumb: 'https://i.ytimg.com/vi/VJoAl1HA_qw/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=VJoAl1HA_qw',
  },
  {
    id: 'hWmlvxVVnSU',
    title: 'Ma diffusion TEST w MTN illimite',
    date: '18 août 2023',
    thumb: 'https://i.ytimg.com/vi/hWmlvxVVnSU/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=hWmlvxVVnSU',
  },
  {
    id: 'rWPNsGRMGjw',
    title: 'Hello dear...',
    date: '9 oct. 2022',
    thumb: 'https://i.ytimg.com/vi/rWPNsGRMGjw/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=rWPNsGRMGjw',
  },
  {
    id: 'ASq6moQ0_ms',
    title: 'Charlotte Dipanda, Locko, Ful, Cysoul, Lydol, Mimie, Isabella, Skriim ... 1an de backstage exclusif',
    date: '24 juin 2022',
    thumb: 'https://i.ytimg.com/vi/ASq6moQ0_ms/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=ASq6moQ0_ms',
  },
  {
    id: 'Qv0FA2Vvrto',
    title: 'Hors série : micro mv7x',
    date: '15 févr. 2022',
    thumb: 'https://i.ytimg.com/vi/Qv0FA2Vvrto/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=Qv0FA2Vvrto',
  },
  {
    id: 'aqIS3XHJSnA',
    title: 'Hors Série : Test Micro',
    date: '28 janv. 2022',
    thumb: 'https://i.ytimg.com/vi/aqIS3XHJSnA/hqdefault.jpg',
    watchUrl: 'https://www.youtube.com/watch?v=aqIS3XHJSnA',
  },
];
